### ISSUE TITLE
0.7.1 Don't work right now

### ISSUE THREAD

**Issue by CatSpaceMarines** [besuper/TwitchNoSub#111]
Paid vods are not playable. Also, streams are not playable. Infinite loading.
https://www.twitch.tv/videos/2160769412
Cent browser

**Comment by mylifeforcrab** [comment]
It's working for me on chrome

**Comment by besuper** [comment]
Hi, it's also working for me. Try to reinstall the extension or try the [userscript](https://raw.githubusercontent.com/besuper/TwitchNoSub/master/userscript/twitchnosub.user.js)

**Comment by r3d5ky** [comment]
It could also be because jsdelivr sometimes seems to block the connection and the script loading gets stuck, at least in my country. With VPN it loads scripts normally. So for myself i changed link to amazon-ivs-worker in the userscript to https://unpkg.com/amazon-ivs-player/dist/assets/amazon-ivs-worker.min.js

Also @CatSpaceMarines, nice choice of streamer to watch, i watch him too (:
So try to use userscript instead and change link for amazon-ivs-worker.min.js file to link above, like this:
```
super(URL.createObjectURL(new Blob(["importScripts('https://cdn.jsdelivr.net/gh/besuper/TwitchNoSub/src/patch_amazonworker.js', 'https://unpkg.com/amazon-ivs-player/dist/assets/amazon-ivs-worker.min.js');"])));
```

**Comment by CatSpaceMarines** [comment]
Thanks a lot, I installed the script and it works!!!
