### ISSUE TITLE
Not working here

### ISSUE THREAD

**Issue by krivbas1** [besuper/TwitchNoSub#75]
https://www.twitch.tv/videos/1812835080

**Comment by Turkceqwertyx** [comment]
it's working for me

**Comment by Turkceqwertyx** [comment]
Which browser do you using? # @krivbas1

**Comment by BlueWorld1** [comment]
Working on my side, not reproductable.

**Comment by onzostudio** [comment]
Indeed, as Blovario said, the problem seems to be related to the recent update of Chromium/Brave. I fixed my problem by checking the extension, disabling it, and then reactivating it after a few seconds. The extension is now working properly. I also disabled Twitch protections, although I believe it is not necessary.

**Comment by Blovario** [comment]
> Indeed, as Blovario said, the problem seems to be related to the recent update of Chromium/Brave. I fixed my problem by checking the extension, disabling it, and then reactivating it after a few seconds. The extension is now working properly. I also disabled Twitch protections, although I believe it is not necessary.

Yep, I did the same : disable, enable and just in case, reload the extension, it worked for me. No need to deactivate twitch protections in my case

**Comment by madmax2** [comment]
@Blovario how do you deactivate twitch extensions?

**Comment by besuper** [comment]
Hi, this should be fixed https://github.com/besuper/TwitchNoSub/commit/601a23b66c87853b5340e4dca91007cc8b3036a2
