### ISSUE TITLE
No work anymore

### ISSUE THREAD

**Issue by imswel** [besuper/TwitchNoSub#77]
**Describe the bug**
Seem to doesn't work anymore. I get this message when I try to watch a replay
![image](https://github.com/besuper/TwitchNoSub/assets/59669359/a0dfe4a9-49b7-45da-aae1-aa3aaa7354db)

**VOD / Channel link**
https://www.twitch.tv/videos/1846239165

**Browser**
Chrome

**Additional context**
I have tried several replays and I always have the same error message.

**Comment by 4164696f73** [comment]
I don't think this error has anything to do with the extension, but I might be wrong. "Error 2000" usually means that there has been a connection failure between your internet and the server you're connecting to, which usually is Twitch's fault. I get this error all the time, on VODs or lives, and it's not specifically tied to any extensions, as far as I know, and I've been using TwitchNoSub for literally less than a day, while getting this error for years since Amazon bought off Twitch.

Though, obviously, if this error pops up every time you try to play something with the extension, there might be something the extension does that is not supported by the Twitch server or other stupid thing that most likely makes no sense anyway.

**Comment by imswel** [comment]
> I don't think this error has anything to do with the extension, but I might be wrong. "Error 2000" usually means that there has been a connection failure between your internet and the server you're connecting to, which usually is Twitch's fault. I get this error all the time, on VODs or lives, and it's not specifically tied to any extensions, as far as I know, and I've been using TwitchNoSub for literally less than a day, while getting this error for years since Amazon bought off Twitch.
> 
> Though, obviously, if this error pops up every time you try to play something with the extension, there might be something the extension does that is not supported by the Twitch server or other stupid thing that most likely makes no sense anyway.

Personally, I had never had this error before.
It seems to only occur on sub-only videos so I think it's related to the extension. I don't get this error anywhere else on twitch.

**Comment by BlueWorld1** [comment]
You issue is not reproductible on my side. Maybe try to clean application file, or private navigation (make sure the extension is enabled is private mode).
But it seems it's linked to your local setup since on my side I have access to the video.

**Comment by Tony-Rambo** [comment]
Got the same issue, it was the Better Twitch Adblock extension for me, if it can help
